apiVersion: addons.sigs.k8s.io/v1alpha1
kind: ConfigManagement
metadata:
  name: nomos-acme
  namespace: config-management-system
spec:
  enableHierarchicalResourceQuota: true
  git:
    secretType: ssh
    syncRepo: git@github.com:michael-madison-wwt/nomos-acme-corp.git
    syncBranch: master
    policyDir: nomos-root

